#-*- coding:utf-8 -*-

"""     This syntax-file was generated by sourceview2codebuffer.xsl from
    GtkSourceView's Python-syntax-file!
    
    This transformation is not perfect so it may need some hand-word to fix
    minor issues in this file.

    You can get sourceview2codebuffer.xsl from 
    http://pygtkcodebuffer.googlecode.com/.
"""

from gtkcodebuffer import Pattern, String, KeywordList, LanguageDefinition  

ld = [String(r'([uUrR]|[uU][rR]|[rR][uU])?"""', r'"""', style="string", 
             escape="\\"),
      String(r"([uUrR]|[uU][rR]|[rR][uU])?'''", r"'''", style="string", 
             escape="\\"),
      String(r'([uUrR]|[uU][rR]|[rR][uU])?"', r'"', style="string", 
             escape="\\"),
      String(r"([uUrR]|[uU][rR]|[rR][uU])?'", r"'", style="string", 
             escape="\\"),
      Pattern(r"#.*$", style="comment"),
      KeywordList(["import","from","as","False", "None", "True", "__name__", 
                   "__debug__"], style="preprocessor"),
      KeywordList(["def","class","return"], style="keyword"),
      KeywordList(["and","assert","break","continue","del","elif","else",
                   "except","exec","finally","for","global","if","in","is",
                   "lambda","not","or","pass","print","raise","try","while",
                   "yield"], style="keyword"),
      KeywordList(
        ["ArithmeticError","AssertionError","AttributeError","EnvironmentError",
         "EOFError","Exception","FloatingPointError","ImportError",
         "IndentationError","IndexError","IOError","KeyboardInterrupt",
         "KeyError","LookupError","MemoryError","NameError",
         "NotImplementedError","OSError","OverflowError","ReferenceError",
         "RuntimeError","StandardError","StopIteration","SyntaxError",
         "SystemError","SystemExit","TabError","TypeError","UnboundLocalError",
         "UnicodeDecodeError","UnicodeEncodeError","UnicodeError",
         "UnicodeTranslateError","ValueError","WindowsError",
         "ZeroDivisionError","Warning","UserWarning","DeprecationWarning",
         "PendingDeprecationWarning","SyntaxWarning","OverflowWarning",
         "RuntimeWarning","FutureWarning","__import__","abs","apply",
         "bool","buffer","callable","chr","classmethod","cmp",
         "coerce","compile","complex","delattr","dict","dir","divmod",
         "enumerate","eval","execfile","file","filter","float","getattr",
         "globals","hasattr","hash","hex","id","input","int","intern",
         "isinstance","issubclass","iter","len","list","locals","long","map",
         "max","min","object","oct","open","ord","pow","property","range",
         "raw_input","reduce","reload","repr","round","setattr","slice",
         "staticmethod","str","sum","super","tuple","type","unichr","unicode",
         "vars","xrange","zip"], style="special"),
      Pattern(r"\\bself\\b", style="datatype"),
      Pattern(r"\\b([1-9][0-9]*|0)([Uu]([Ll]|LL|ll)?|([Ll]|LL|ll)[Uu]?)?\\b", 
              style="number"),
      Pattern(r"\\b([0-9]+[Ee][-]?[0-9]+|([0-9]*\.[0-9]+|[0-9]+\.)([Ee][-]?[0-9]+)?)[fFlL]?", 
              style="number"),
      Pattern(r"\\b([1-9][0-9]*|0)([Uu]([Ll]|LL|ll)?|([Ll]|LL|ll)[Uu]?)?\\b", 
              style="number"),
      Pattern(r"\\b0[0-7]+([Uu]([Ll]|LL|ll)?|([Ll]|LL|ll)[Uu]?)?\\b", 
              style="number"),
      Pattern(r"\\b0[xX][0-9a-fA-F]+([Uu]([Ll]|LL|ll)?|([Ll]|LL|ll)[Uu]?)?\\b", 
              style="number"),
    ]
lang = LanguageDefinition(ld)